env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'mediamonkey'
ignorePatterns: ['**/*.js'] # disable eslint on all js files
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-prototype-builtins: off
  prefer-const: off
  no-empty-function: off
  no-constant-condition:
    - error
    - checkLoops: false
  no-var: off
  mediamonkey/no-var-except-declare: error
  prefer-rest-params: warn
  no-misleading-character-class: off # JL note: Not sure what to do about this one
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-this-alias": warn # JL note: It'd be worth eventually moving away from "this" aliases and switching to arrow functions, so I believe a warn is acceptable
  "@typescript-eslint/ban-ts-comment": warn # JL note: we need many instances of @ts-ignore for compatibility purposes but it's worth keeping the warning