

// Mask Items:
const
    MI_EMPTY = 1,
    MI_SEPARATOR = 2,
    MI_BACKSLASH = 3,
    MI_TITLE = 4,
    MI_FILENAME = 5,
    MI_TRACKNUMBER = 6,
    MI_AUTONUMBER = 7,
    MI_RANDOM = 8,
    MI_PLAYLIST = 9,
    MI_ARTIST = 10,
    MI_ALBUMARTIST = 11,
    MI_ALBUM = 12,
    MI_GENRE = 13,
    MI_YEAR = 14,
    MI_COMPOSER = 15,
    MI_BITRATE = 16,
    MI_BPM = 17,
    MI_FOLDER = 18,
    MI_CUSTOM1 = 19,
    MI_CUSTOM2 = 20,
    MI_CUSTOM3 = 21,
    MI_CUSTOM4 = 22,
    MI_CUSTOM5 = 23,
    MI_HELP = 24,
    MI_DISCNUMBER = 25,
    MI_GROUPING = 26,
    MI_CONDUCTOR = 27,
    MI_DATE = 28,
    MI_SKIP = 29,
    MI_LYRICIST = 30,
    MI_RATING = 31,
    MI_TEMPO = 32,
    MI_MOOD = 33,
    MI_OCCASION = 34,
    MI_QUALITY = 35,
    MI_ORIGINALARTIST = 36,
    MI_ORIGINALLYRICIST = 37,
    MI_ORIGINALTITLE = 38,
    MI_PATH = 39,
    MI_EXTENSION = 40,
    MI_ORIGINALDATE = 41,
    MI_PUBLISHER = 42,
    MI_DATEADDED = 43,
    MI_TARGET_EXTENSION = 44,
    MI_PODCAST = 45,
    MI_SERIES = 46,
    MI_PRODUCER = 47,
    MI_DIRECTOR = 48,
    MI_EPIS_NUM = 49,
    MI_SEASON_NUM = 50,
    MI_ACTORS = 51,
    MI_TRACKLENGTH = 52,
    MI_TYPE = 53,
    MI_SAMPLERATE = 54,
    MI_PARENTALRATING = 55,
    MI_INVOLVEDPEOPLE = 56,
    MI_LYRICS = 57,
    MI_INITIAL_KEY = 58,
    MI_SOURCE = 59,
    MI_PLAYCOUNTER = 60,
    MI_LASTPLAYED = 61,
    MI_MEDIA = 62,
    MI_FILESIZE = 63,
    MI_CHANNELS = 64,
    MI_BPS = 65,
    MI_TRACKVOLUME = 66,
    MI_ALBUMVOLUME = 67,
    MI_TIMESTAMP = 68,
    MI_SUMMARY = 69,
    MI_RESOLUTION = 70,
    MI_FRAMERATE = 71,
    MI_AUTHOR = 72,
    MI_SCREENWRITER = 73,
    MI_ISRC = 74,
    MI_COPYRIGHT = 75,
    MI_ENCODER = 76,
    MI_CUSTOM6 = 77,
    MI_CUSTOM7 = 78,
    MI_CUSTOM8 = 79,
    MI_CUSTOM9 = 80,
    MI_CUSTOM10 = 81,
    MI_SKIPCOUNT = 82,
    MI_COMMENT = 83;

let MaskNames = [
    '', '', '-', '\\',

    'S', 'F', 'T', 'D', 'N', 'Q', 'A', 'R', 'L', 'G', 'Y', 'C', 'B',
    'M', 'P', 'U', 'V', 'W', 'J', 'K', 'Help',
    'ZM', 'ZO', 'ZN', 'ZP', 'X', 'ZG', 'ZR', 'ZC', 'ZA', 'ZB', 'ZL',
    'ZH', 'ZI', 'ZJ', 'O', 'E', 'ZS', 'ZK', 'ZT', 'ZQ', 'ZU', 'ZV',
    'ZW', 'ZX', 'ZY', 'ZZA', 'ZZB', 'H', 'ZZC', 'ZZD', 'ZZE', 'ZZF',
    'ZZG', 'ZZH', 'ZZI', 'ZZJ', 'ZZK', 'ZZM', 'ZZL', 'ZZN', 'ZZO', 'ZZP',
    'ZZQ', 'ZZR', 'ZZS', 'ZZT', 'ZZU', 'ZZV', 'ZZW', 'ZF', 'ZZX', 'ZE',
    'ZZ0', 'ZZ1', 'ZZ2', 'ZZ3', 'ZZ4', 'ZZ5', 'ZD'
];

let MaskPack_Details = [
    MI_TITLE, MI_ARTIST, MI_ACTORS, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_ALBUMARTIST, MI_TRACKLENGTH,
    MI_TRACKNUMBER, MI_EPIS_NUM, MI_DISCNUMBER, MI_SEASON_NUM, MI_FILENAME,
    MI_GENRE, MI_YEAR, MI_COMPOSER, MI_PRODUCER, MI_BITRATE, MI_BPM, MI_FOLDER, MI_CUSTOM1,
    MI_CUSTOM2, MI_CUSTOM3, MI_CUSTOM4, MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10,
    MI_GROUPING, MI_CONDUCTOR, MI_DIRECTOR, MI_DATE,
    MI_LYRICIST, MI_RATING, MI_TEMPO, MI_MOOD, MI_OCCASION, MI_QUALITY, MI_ORIGINALARTIST,
    MI_ORIGINALLYRICIST, MI_ORIGINALTITLE, MI_PATH, MI_EXTENSION, MI_ORIGINALDATE, MI_PUBLISHER,
    MI_DATEADDED, MI_TYPE, MI_SAMPLERATE, MI_BPS, MI_PARENTALRATING, MI_INVOLVEDPEOPLE, MI_LYRICS, MI_INITIAL_KEY
];

let MaskPack_Browser = [
    MI_ARTIST, MI_COMPOSER, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GROUPING,
    MI_CONDUCTOR, MI_LYRICIST, MI_DATE, MI_GENRE, MI_RATING, MI_TEMPO,
    MI_MOOD, MI_OCCASION, MI_QUALITY, MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3,
    MI_CUSTOM4, MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10,
    MI_FOLDER, MI_ORIGINALARTIST, MI_ORIGINALLYRICIST, MI_ORIGINALTITLE
];

let MaskPack_Rip = [
    MI_TITLE, MI_FILENAME, MI_TRACKNUMBER, MI_EPIS_NUM, MI_AUTONUMBER, MI_RANDOM,
    MI_EMPTY,
    MI_BACKSLASH, MI_SEPARATOR,
    MI_EMPTY,
    MI_ARTIST, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GENRE, MI_YEAR,
    MI_COMPOSER, MI_PRODUCER, MI_CONDUCTOR, MI_DIRECTOR, MI_PUBLISHER,
    MI_BITRATE, MI_BPM, MI_FOLDER, MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3, MI_CUSTOM4,
    MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10,
    MI_GROUPING, MI_INITIAL_KEY, MI_TARGET_EXTENSION,
    MI_EMPTY, MI_HELP
];

let MaskPack_Convert = [
    MI_TITLE, MI_FILENAME, MI_DISCNUMBER, MI_SEASON_NUM, MI_TRACKNUMBER, MI_EPIS_NUM,
    MI_AUTONUMBER, MI_RANDOM,
    MI_EMPTY,
    MI_BACKSLASH, MI_SEPARATOR,
    MI_EMPTY,
    MI_ARTIST, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GENRE, MI_YEAR, MI_DATE,
    MI_COMPOSER, MI_PRODUCER, MI_CONDUCTOR, MI_DIRECTOR, MI_PUBLISHER,
    MI_BITRATE, MI_BPM, MI_FOLDER, MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3, MI_CUSTOM4,
    MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10,
    MI_GROUPING, MI_EXTENSION, MI_INITIAL_KEY, MI_TARGET_EXTENSION,
    MI_EMPTY, MI_HELP
];

let MaskPack_Def = [
    MI_TITLE, MI_FILENAME, MI_TRACKNUMBER, MI_EPIS_NUM, MI_AUTONUMBER, MI_RANDOM,
    MI_EMPTY,
    MI_BACKSLASH, MI_SEPARATOR,
    MI_EMPTY,
    MI_ARTIST, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GENRE, MI_YEAR, MI_DATE,
    MI_COMPOSER, MI_PRODUCER, MI_CONDUCTOR, MI_DIRECTOR, MI_PUBLISHER,
    MI_BITRATE, MI_BPM, MI_FOLDER, MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3, MI_CUSTOM4,
    MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10, MI_GROUPING, MI_INITIAL_KEY
];

let MaskPack_Def_WithHelp = [
    MI_TITLE, MI_FILENAME, MI_DISCNUMBER, MI_SEASON_NUM, MI_TRACKNUMBER, MI_EPIS_NUM,
    MI_AUTONUMBER, MI_RANDOM,
    MI_EMPTY,
    MI_BACKSLASH, MI_SEPARATOR,
    MI_EMPTY,
    MI_ARTIST, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GENRE, MI_YEAR, MI_DATE,
    MI_COMPOSER, MI_PRODUCER, MI_CONDUCTOR, MI_DIRECTOR, MI_PUBLISHER,
    MI_BITRATE, MI_BPM, MI_FOLDER, MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3, MI_CUSTOM4,
    MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10, MI_GROUPING, MI_EXTENSION,
    MI_EMPTY, MI_HELP
];

let MaskPack_Def_WithHelpAndPlaylist = [
    MI_TITLE, MI_FILENAME, MI_DISCNUMBER, MI_SEASON_NUM, MI_TRACKNUMBER, MI_EPIS_NUM,
    MI_AUTONUMBER, MI_RANDOM,
    MI_EMPTY,
    MI_BACKSLASH, MI_SEPARATOR,
    MI_EMPTY,
    MI_PLAYLIST, MI_ARTIST, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GENRE, MI_YEAR, MI_DATE,
    MI_COMPOSER, MI_PRODUCER, MI_CONDUCTOR, MI_DIRECTOR, MI_PUBLISHER,
    MI_BITRATE, MI_BPM, MI_FOLDER, MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3,
    MI_CUSTOM4, MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10, MI_GROUPING, MI_EXTENSION,
    MI_EMPTY,
    MI_HELP
];

let MaskPack_Def_AutoTag = [
    MI_TITLE, MI_DISCNUMBER, MI_SEASON_NUM, MI_TRACKNUMBER, MI_EPIS_NUM,
    MI_EMPTY,
    MI_BACKSLASH, MI_SEPARATOR,
    MI_EMPTY,
    MI_ARTIST, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GENRE, MI_YEAR, MI_COMPOSER, MI_PRODUCER,
    MI_CONDUCTOR, MI_DIRECTOR, MI_PUBLISHER, MI_BITRATE, MI_BPM, MI_FOLDER,
    MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3, MI_CUSTOM4, MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10, MI_GROUPING, MI_INITIAL_KEY,
    MI_EMPTY,
    MI_SKIP,
    MI_EMPTY,
    MI_HELP
];

let MaskPack_Def_AutoTagFromFilename = [
    MI_TITLE, MI_DISCNUMBER, MI_SEASON_NUM, MI_TRACKNUMBER, MI_EPIS_NUM,
    MI_EMPTY,
    MI_BACKSLASH, MI_SEPARATOR,
    MI_EMPTY,
    MI_ARTIST, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GENRE, MI_YEAR, MI_COMPOSER, MI_PRODUCER,
    MI_CONDUCTOR, MI_DIRECTOR, MI_PUBLISHER, MI_ACTORS, MI_PARENTALRATING, MI_INVOLVEDPEOPLE, MI_BITRATE, MI_BPM, MI_FOLDER,
    MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3, MI_CUSTOM4, MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10, MI_GROUPING, MI_INITIAL_KEY,
    MI_EMPTY,
    MI_SKIP,
    MI_EMPTY,
    MI_HELP
];

let MaskPack_Def_VirtualCDAndPreview = [
    MI_TITLE, MI_FILENAME, MI_DISCNUMBER, MI_SEASON_NUM, MI_TRACKNUMBER, MI_EPIS_NUM,
    MI_EMPTY,
    MI_BACKSLASH, MI_SEPARATOR,
    MI_EMPTY,
    MI_ARTIST, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GENRE, MI_YEAR, MI_COMPOSER, MI_CONDUCTOR,
    MI_BITRATE, MI_BPM, MI_FOLDER,
    MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3, MI_CUSTOM4, MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10, MI_GROUPING,
    MI_EMPTY,
    MI_HELP
];

let MaskPack_DefWithPlaylist = [
    MI_TITLE, MI_FILENAME, MI_DISCNUMBER, MI_SEASON_NUM, MI_TRACKNUMBER, MI_EPIS_NUM,
    MI_AUTONUMBER, MI_PLAYLIST, MI_RANDOM,
    MI_EMPTY,
    MI_BACKSLASH, MI_SEPARATOR,
    MI_EMPTY,
    MI_ARTIST, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GENRE, MI_YEAR, MI_DATE,
    MI_COMPOSER, MI_CONDUCTOR, MI_BITRATE,
    MI_BPM, MI_FOLDER, MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3, MI_CUSTOM4, MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10, MI_GROUPING, MI_INITIAL_KEY,
    MI_EMPTY,
    MI_HELP
];

let MaskPack_ThePrefix = [
    MI_TITLE, MI_ARTIST, MI_ALBUMARTIST, MI_ALBUM, MI_PODCAST, MI_SERIES, MI_GENRE, MI_COMPOSER, MI_PRODUCER,
    MI_CONDUCTOR, MI_DIRECTOR, MI_PUBLISHER, MI_ACTORS, MI_PARENTALRATING, MI_INVOLVEDPEOPLE,
    MI_CUSTOM1, MI_CUSTOM2, MI_CUSTOM3, MI_CUSTOM4, MI_CUSTOM5, MI_CUSTOM6, MI_CUSTOM7, MI_CUSTOM8, MI_CUSTOM9, MI_CUSTOM10, MI_GROUPING
];

function addMasks(ar, list) {
    for (let i = 0; i < ar.length; i++) {
        ODS('Adding mask %' + MaskNames[ar[i]]);
        if(ar[i] !== MI_SEPARATOR)
            list.add('%' + MaskNames[ar[i]]);
        else
            list.add('-');
    }
}

/**
    Gets list of mask IDs for specified preset. Available presets are:
    default, default_with_help, default_with_help_and_playlist, details, browser, rip, convert,
    default_autotag, default_autotag_from_filename, default_virtualcd, default_with_playlist

    @method getPredefinedMasks
    @param {string} presetName Preset name
    @return {StringList}
*/
window.getPredefinedMasks = function (presetName) {
    ODS('Loading masks for preset ' + presetName);
    let result = newStringList();
    if (presetName == 'default_with_help')
        addMasks(MaskPack_Def_WithHelp, result);
    else if (presetName == 'default_with_help_and_playlist')
        addMasks(MaskPack_Def_WithHelpAndPlaylist, result);
    else if (presetName == 'details')
        addMasks(MaskPack_Details, result);
    else if (presetName == 'preview')
        addMasks(MaskPack_Details.concat([MI_COMMENT]), result); // #17093
    else if (presetName == 'browser')
        addMasks(MaskPack_Browser, result);
    else if (presetName == 'rip')
        addMasks(MaskPack_Rip, result);
    else if (presetName == 'convert')
        addMasks(MaskPack_Convert, result);
    else if (presetName == 'default_autotag')
        addMasks(MaskPack_Def_AutoTag, result);
    else if (presetName == 'default_autotag_from_filename')
        addMasks(MaskPack_Def_AutoTagFromFilename, result);
    else if (presetName == 'default_virtualcd')
        addMasks(MaskPack_Def_VirtualCDAndPreview, result);
    else if (presetName == 'default_with_playlist')
        addMasks(MaskPack_DefWithPlaylist, result);
    else if (presetName == 'removePrefixTheFields')
        addMasks(MaskPack_ThePrefix, result);
    else
        addMasks(MaskPack_Def, result);
    return result;
};


