/* 'This file is part of MediaMonkey licensed for use under the Ventis Media End User License Agreement, and for the creation of derivative works under the less restrictive Ventis Limited Reciprocal License. See: https://www.mediamonkey.com/sw/mmw/5/Ventis_limited_reciprocal_license.txt' */

const fs = require('fs');
const { join, basename, dirname, relative } = require('path');

const TS_DIR = join(__dirname, '..', 'src');
const OUT_DIR = join(TS_DIR, 'types');

if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR);

console.log(`Outputting to ${OUT_DIR}`);

// here is where we declare which files and whatnot are placed into types, for tsdoc purposes
createGroupExportFromDir('controls', 'Controls.ts', `
/**
 * This module contains classes for _controls_ which let you control the UI with your JS code.
 * 
 * The base class is {@link Controls.control}, which also exports a few helper functions, e.g. {@link getPixelSize} which may be used in other controls.
 * 
 *      import Control from './control';
 * 
 *      class MyCustomControl extends Control \\{
 *          initialize(rootelem, params) \\{
 *              // ...
 *          \\}
 *      \\}
 * 
 * @packageDocumentation
 */
`);
createGroupExportFromDir('helpers', 'Helpers.ts');

// createGroupExportFromFile('actions.ts', 'actions.ts', '..');
// createGroupExportFromFile('uitools.ts', 'uitools.ts', '..');
// createGroupExportFromFile('viewHandlers.ts', 'viewHandlers.ts', '..');

function createGroupExportFromFile(fileToRead, outputFile, startComment) {
	fileToRead = join(TS_DIR, fileToRead);
	outputFile = join(OUT_DIR, outputFile);
	createGroupExport(dirname(fileToRead), [basename(fileToRead)], outputFile, startComment);
}

function createGroupExportFromDir(dirToRead, outputFile, startComment) {
	dirToRead = join(TS_DIR, dirToRead);
	outputFile = join(OUT_DIR, outputFile);
	// const files = fs.readdirSync(dirToRead);
	// createGroupExport(dirToRead, files, outputFile, relativePath, startComment);
	// Recursively get a list of all files in dirToRead
	const files = [];
	const walk = (dir) => {
		let list = fs.readdirSync(dir);
		for (let file of list) {
			let path = join(dir, file);
			let stats = fs.statSync(path);
			if (stats.isDirectory()) {
				walk(path);
			}
			else {
				files.push(path);
			}
		}
	};
	walk(dirToRead);
	createGroupExport(dirToRead, files, outputFile, startComment);
}

function createGroupExport(baseDir, files, outputFile, startComment) {
	const defaultExportRegex = /^ *export default \w*? (\w*)/gim;
	const regularExportRegex = /^ *export (?:declare )*(?!default)\w*? (\w*)/gim;
	
	let outString = '// This file was auto-generated by the parseTS script for Typedoc. \n\n';
    
    if (startComment)
        outString += startComment + '\n\n';
    
	for (let filepath of files) {
		const filename = basename(filepath);
		const fileContents = fs.readFileSync(filepath, 'utf-8');
		const filenameWithoutExt = filename.split('.')[0];
		
		// Find the file's default export
		let defaultExport;
		let defaultExportMatches = fileContents.matchAll(defaultExportRegex);
		if (defaultExportMatches) {
			for (let match of defaultExportMatches) {
				defaultExport = match[1]; // 1st captured group
			}
		}
		
		// Calculate relative path from outputFile to the directory containing filepath
		let relativePath = relative(dirname(outputFile), dirname(filepath)).replace(/\\/g, '/');
		
		// Find the file's regular exports, if any
		let regularExports = [];
		let regularExportMatches = fileContents.matchAll(regularExportRegex);
		if (regularExportMatches) {
			for (let match of regularExportMatches) {
				regularExports.push(match[1]); // 1st captured group
			}
		}
		
		// if the file exports something
		if (defaultExport || (regularExports.length > 0)) {
			let exportStringArr = [];
			if (defaultExport) exportStringArr.push(`default as ${defaultExport}`);
			exportStringArr.push(...regularExports);
			outString += `export {${exportStringArr.join(', ')}} from '${relativePath}/${filenameWithoutExt}';\n`;
		}
	}
    console.log(`Writing to file ${outputFile}`);
	fs.writeFileSync(outputFile, outString, 'utf-8');
}